### PR TITLE
Optimize SVG

### PR DESCRIPTION
**Pull request by ValentinTh**
The icon wasn't showing all the details initially created (double ring + interrogation point, not showed)

### CODE REVIEW

**Comment by MrMicky-FR** [comment]
Hi, can you send a screenshot of the issue, and also on which browser and platform this issue occurs ? Because it’s working fine for me, and using base64 inside a SVG file is not really clean and in this case it increase the file size by 3280% (1.78 kb -> 58.4 kb)

**Comment by ValentinTh** [comment]
My bad indeed.
It's okay on chrome, not on SAFARI Version 12.1.1 (14607.2.6.1.1) MacOS
https://prnt.sc/1tdbyjm

Regarding the SVG generation, I used PS included SVG generator, I have no clue on how to generate it differently.
(If you have tips I'm listening ;) )

**Comment by MrMicky-FR** [comment]
I don’t use Photoshop but make sure to import the images as vectors (like SVG)

**Comment by MrMicky-FR** [comment]
Hi @ValentinTh, I’m trying to find the issue, but as I don’t have a mac, could you please send me a screenshot with Safari v12 of the 3 images on this page https://jsfiddle.net/w5mna2ex/ ?
Thanks

**Comment by ValentinTh** [comment]
Hi,
https://prnt.sc/1tlbzmf

**Comment by MrMicky-FR** [comment]
Hi, thanks, well sometimes Safari is… interesting 🤔

I’ve updated with the SVG of the middle icon as it’s a good visual compromise and it prevent increasing massively the size of the file for everyone, with a benefit only for Safari v12 which is used by only less than 1% of users (and maybe v13, but looks like it’s fixed in v14)

_(Also optimized an other icon while I was here)_

**Pull request merged**
