### PR TITLE
Add Korean Translation

### PR DESCRIPTION
**Pull request by imirochi**
Missing docs currently, wish I can finish all of em til this week

### CODE REVIEW

**Comment by MrMicky-FR** [comment]
Great, thanks a lot! I’ve marked this as a draft until it’s ready (then you can mark it as done and/or ping me, but no worries take your time) 😃

**Comment by MrMicky-FR** [comment]
Hu, thanks for the work, any updates on this? Is it ready or not yet? Thx!

**Comment by imirochi** [comment]
Sorry I was a bit busy recently. I'll restart translation and probably finishes in this week!

**Comment by MrMicky-FR** [comment]
Unfortunately I'm closing this for inactivity and conflicts 😕 Feel free to comment or open an other pull request if you are still interested in the Korean translation

**Pull request closed without merging**
