### PR TITLE
Add NiHost logo

### PR DESCRIPTION
**Pull request by ValentinTh**
Addition to illustrate the provider recommendation banner in documentation

### CODE REVIEW

**Comment by MrMicky-FR** [comment]
Where this icon would be used in the documentation ? Because now the image is added but isn’t display anywhere.

Also would be better to use a real SVG rather than using a base64 image in a SVG file

**Comment by ValentinTh** [comment]
https://azuriom.com/fr/docs/installation : <<info>> section
Same issue, if you have tips to generate and lower the size don't hesitate ;)

**Comment by ValentinTh** [comment]
Hi @MrMicky-FR,
Any news?
Is it better with the last pull ?

**Comment by MrMicky-FR** [comment]
Yes, great I’ve just updated the documentation so the logo is actually displayed, and also just slightly optimized the logo to reduce further its size

**Comment by ValentinTh** [comment]
Perfect !

**Pull request merged**
