### PR TITLE
German added

### PR DESCRIPTION
**Pull request by Justman10000**
Please do not change anything or integrate it into the website, as this is still in the beta! Please do not cooperate either, as I will finish this in a very short time... I will install the updates here one by one and announce when it is ready...

### CODE REVIEW

**Comment by MrMicky-FR** [comment]
> Please do not change anything or integrate it into the website, as this is still in the beta! Please do not cooperate either, as I will finish this in a very short time... I will install the updates here one by one and announce when it is ready...

Sure np, I’ve marked this as draft until is ready

**Comment by MrMicky-FR** [comment]
The flags are from

**Comment by Justman10000** [comment]
> 
> 
> The flags are from https://twemoji.twitter.com/

And how do I find a specific country flag? The names are all only shown in codes!

**Comment by MrMicky-FR** [comment]
For the german flag 🇩🇪 : https://github.com/twitter/twemoji/blob/master/assets/svg/1f1e9-1f1ea.svg

**Comment by MrMicky-FR** [comment]
You can use [this website](https://unicode.org/emoji/charts/full-emoji-list.html)

**Comment by Justman10000** [comment]
German translation completed! Ready for the release of Alpha Version 1.0

**Comment by Justman10000** [comment]
@MrMicky-FR

**Comment by Justman10000** [comment]
@MrMicky-FR 

German translation completed! Ready for the release of Alpha Version 1.0

**Comment by MrMicky-FR** [comment]
Hi, looks great, thanks a lot ! 
Just looks line the `title` section at the tops of the .md files aren’t translated yet, as well as the home link in the navbar.

I’ve also updated the config, so the german preview is now available here: https://deploy-preview-8--azuriom.netlify.app/de/

**Comment by Justman10000** [comment]
@MrMicky-FR 

So?

**Comment by MrMicky-FR** [comment]
Great, just didn’t saw it before but the AzLink page isn’t translated: https://deploy-preview-8--azuriom.netlify.app/de/azlink

**Comment by Justman10000** [comment]
But somehow it has no effect!

**Comment by Justman10000** [comment]
> 
> 
> Hi, I fixed the issues, is it ready for you so I can merge ? For me looks good 👍

I deleted this because I couldn't see any differences in my instance! But yes, everything else is ready!

**Comment by MrMicky-FR** [comment]
Great thanks !

**Comment by Justman10000** [comment]
> 
> 
> Great thanks !

I will also keep it updated in case there are any updates...

**Pull request merged**
