### PR TITLE
Updated Documentation. (Dutch)

### PR DESCRIPTION
**Pull request by Fabian-Evolved**
Sorry it took longer, had private life stuff going on.

Added all the latest changes to the documentation in the Dutch version of it. Including customgames.md translated to Dutch.

Also fixed a typo in the english custom games doc. from `ressources` to `resources`.

### CODE REVIEW

**Comment by Fabian-Evolved** [comment]
This PR depends on the https://github.com/Azuriom/azuriom.com/pull/40 being added beforehand. as this PR includes the Dutch translations of the PR mentioned in this comment.

**Comment by Fabian-Evolved** [comment]
Updated the Dutch documentation to reflect the latest additions to the Azuriom English documentation.
This PR still depends on #40 before being accepted.

This PR also fixes a typo within the English documentation where it says:

`The website be in version 0.6.0` is changed to `The website must be in version 0.6.0` adding the word MUST in between website and be, as the first sentence isn't proper English.

**Comment by Fabian-Evolved** [comment]
Again added latest commit from the English documentation to the Dutch version.

**Comment by MrMicky-FR** [comment]
Great thanks ✨

**Pull request merged**
